#! bin/bash
# This script provides a generic deployment configuration base to initialize a server so it con be configured with puppet
#
# Author: pierre@pvln.nl
# Usage : bash ./deployment_base 
#
echo 0.0 Starting deployment_base ...

# ==========================================
# SET VARIABLES
# =========================================
#
# no spaces in variables!
#
MYDEPLOYMENTUSERNAME="myDep"
MYDEPLOYMENTPASSWORD="myDep"
MYDEPLOYMENTDIRECTORY=/home/$MYDEPLOYMENTUSERNAME
MYDEPLOYMENTHOSTNAME="voluntas-v0.0.1"

echo 1.0 Deployment user ...
# ==========================================
# DEPLOYMENT USER AND GROUP
# ==========================================
echo 1.1 Checking if deployment user $MYDEPLOYMENTUSERNAME exists if not create it ...
[[ $(cat /etc/passwd | grep $MYDEPLOYMENTUSERNAME | sed -e 's/:.*//g') =~ $MYDEPLOYMENTUSERNAME ]] ||  sudo useradd -m $MYDEPLOYMENTUSERNAME
#set password for user
#
# Inspiration: https://ccm.net/faq/790-changing-password-via-a-script
#
echo -e "$MYDEPLOYMENTPASSWORD\n$MYDEPLOYMENTPASSWORD" | (sudo passwd $MYDEPLOYMENTUSERNAME)

echo 1.2 Checking if directory $MYDEPLOYMENTDIRECTORY exists if not create it ...
#
# Inspiration: https://unix.stackexchange.com/questions/247576/how-to-get-home-given-user
#              https://stackoverflow.com/questions/42979293/creating-a-home-directory-for-a-user
#
#[[ $(getent passwd $MYDEPLOYMENTUSERNAME | cut -d: -f6) == "" ]] || sudo mkdir /home/$MYDEPLOYMENTUSERNAME && sudo usermod -d /home/$MYDEPLOYMENTUSERNAME $MYDEPLOYMENTUSERNAME
if [ ! -d "$MYDEPLOYMENTDIRECTORY" ]; then
  sudo mkdir "$MYDEPLOYMENTDIRECTORY"
fi

echo 2.0 Timezone ...
# ==========================================
# CONFIGURE TIMEZONE AND LOCALTIME
# ==========================================
#
# Inspiration: https://www.tecmint.com/set-time-timezone-and-synchronize-time-using-timedatectl-command/
#              https://stackoverflow.com/questions/12375722/how-do-i-test-in-one-line-if-command-output-contains-a-certain-string/12375792
#              https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found/12230723
#
echo 2.1 Check if timezone is Europe/Amsterdam if not change it ...
[[ $(timedatectl | grep "Time zone") =~ "Europe/Amsterdam" ]] || sudo timedatectl set-timezone "Europe/Amsterdam"

#echo 3.0 Setting hostname to $MYDEPLOYMENTHOSTNAME ...
## ==========================================
## SET HOSTNAME
## ==========================================
##
## Hostname should be the same as manifestfilename for puppet
##
#sudo hostname $MYDEPLOYMENTHOSTNAME
#echo $MYDEPLOYMENTUSERNAME >hostname
#sudo cp hostname /etc
## when server is rebooted it will have the new hostname

echo 4.0 Required Programs
# ==========================================
# PROGRAMS
# ==========================================
#

echo 5.0 Required configuration files
# ==========================================
# CONFIGURATION FILES
# ==========================================
#
cd /home/$MYDEPLOYMENTUSERNAME
sudo mkdir -p puppet/manifests
sudo mkdir -p puppet/modules
# get host manifest file
sudo wget -q https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/puppet/manifests/$MYDEPLOYMENTHOSTNAME.pp -O puppet/manifests/$MYDEPLOYMENTHOSTNAME.pp
# get modules files as part of the entire project from github
sudo curl -L -o master.zip http://github.com/pierre-pvln/servers_baseline/zipball/master/
#extract only the contents of the modules folder

echo 6.0 Finalize..
# ==========================================
# FINALIZE
# ==========================================
#
echo 6.1 Setting ownership of directory $MYDEPLOYMENTDIRECTORY and all files in it to $MYDEPLOYMENTUSERNAME ...
sudo chown -R $MYDEPLOYMENTUSERNAME:$MYDEPLOYMENTUSERNAME $MYDEPLOYMENTDIRECTORY

echo 6.2 Adding user to sudo group
sudo usermod -aG sudo $MYDEPLOYMENTUSERNAME

echo 7.0 Deployment base created ...
# ==========================================
# DONE
# ==========================================
#
echo 7.1 You should now logout and login with $MYDEPLOYMENTUSERNAME
