#! bin/bash
# This script gets the latest version of the various scriptfiles from github
#
# Author: pierre@pvln.nl
# Usage : bash ./run_wget 
#

cd ~
wget -q https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/rpi3-raspbian9/node/deployment_base -O ./deployment_base
wget -q https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/rpi3-raspbian9/node/run_puppet -O ./run_puppet
wget -q https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/rpi3-raspbian9/node/run_wget -O ./run_wget
