#! bin/bash
# This script gets the latest version of the various scriptfiles from github
#
# Author: pierre@pvln.nl
# Usage : bash ./run_wget 
#

cd ~
echo Retrieving deployment_base
wget https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/hw-os/rpi3-raspbian9/node/deployment_base -O ./deployment_base

echo Retrieving run_puppet
wget https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/hw-os/rpi3-raspbian9/node/run_puppet -O ./run_puppet

echo Retrieving run_wget
wget https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/hw-os/rpi3-raspbian9/node/run_wget -O ./run_wget
