#! bin/bash
# This script runs puppet to configure the node
#
# Author: pierre@pvln.nl
# Usage : bash ./run_puppet 
#
echo 0.0 Starting puppet ...
puppet --version
if [ $? -eq 0 ]; then
    puppet apply --modulepath=/home/myDep/puppet/modules /home/myDep/puppet/manifests/site.pp
else
    echo Puppet not installed
fi

echo 7.0 Puppet run done ...
