#! bin/bash
# This script gets the latest version of the various scriptfiles from github
#
# Author: pierre@pvln.nl
# Usage : bash ./run_wget 
#

cd ~
#echo Retrieving deployment_base
wget -q --show-progress https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/hw-os/rpi3-raspbian9/node/deployment_base -O ./deployment_base

#echo Retrieving run_puppet
wget -q --show-progress https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/hw-os/rpi3-raspbian9/node/run_puppet -O ./run_puppet

#echo Retrieving run_wget
wget -q --show-progress https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/hw-os/rpi3-raspbian9/node/run_wget -O ./run_wget

#echo Retrieving run_wget
wget -q --show-progress https://raw.githubusercontent.com/pierre-pvln/servers_baseline/master/hw-os/rpi3-raspbian9/node/reset_hostname -O ./run_wget
